"""add persona avatar_url

Revision ID: 50a4573149f1
Revises: 1ccba81cdd20
Create Date: 2026-06-25 10:57:40.235324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a4573149f1'
down_revision: Union[str, Sequence[str], None] = '1ccba81cdd20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'client_msg_id')
    op.add_column('persona', sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona', 'avatar_url')
    op.add_column('messages', sa.Column('client_msg_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
